### ISSUE TITLE
why don't we leverage the hidden state to achieve infinite ctx_len? 

### ISSUE THREAD

**Issue by typoverflow** [max7born/decision-lstm#1]
Hi, 
thanks for open-sourcing the code! I was also interested in substituting the GPT2 with RNN-like structures in Decision Transformers. I thought the primary advantage of using RNN is, we can pass the hidden states across segments of trajectories to achieve infinite ctx-len in theory, rather than a fixed length as in DT. I noticed that you used fixed and zero hidden and cell state for DecisionLSTM, why don't we leverage the hidden state?

**Comment by max7born** [comment]
Hi @typoverflow ,

Thank you for your interest in our paper and code! 

The hidden and cell state might in theory enable the RNN-like extensions of DT to have infinite context length, but we assume that in practice the context length will still be limited because we expect the RNN to suffer from long-term dependency problems after a certain context length has been reached. However, it would be interesting to investigate these capabilities in more detail. 

Let me know if you have other questions 🙂

Best,
Max
